--Создаем таблицу с жанрами
CREATE TABLE IF NOT EXISTS genre (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(48)
);
--Создаем таблицу с фильмами с внешним ключем genre_id которая ссылается на поле id
--таблицы genre
    CREATE TABLE IF NOT EXISTS films (
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(48),
    release_date date ,
    duration INTEGER,
    description varchar(200),
    genre_id INTEGER REFERENCES genre (genre_id),
    rating varchar(10)
    );

-- Создаем таблицу пользователей
    CREATE TABLE IF NOT EXISTS users (
      	user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      	name varchar(48),
      	login varchar(48),
      	email varchar(48),
      	birthday date
    );

--Создаем таблицу добавления в друзья.
    CREATE TABLE  IF NOT EXISTS adding_friends(
        adding_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        from_user_id INTEGER REFERENCES users(user_id),
        to_user_id INTEGER REFERENCES users(user_id),
        status boolean
    );

--Создае таблицу лайков фильма
CREATE TABLE IF NOT EXISTS likes(
   like_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   film_id INTEGER REFERENCES films(film_id),
   user_id INTEGER REFERENCES users(user_id)

);

